export enum SortBy {
  NONE = "NONE",
  NAME = "NAME",
  SURNAME = "SURNAME",
  PATRONYMIC = "PATRONYMIC",
  AGE = "AGE",
  MIDDLE_BALANCE = "MIDDLE_BALANCE",
  MAX_BALANCE = "MAX_BALANCE",
  MIN_BALANCE = "MIN_BALANCE",
}